### ISSUE TITLE
Test your Poker Agents on pokerwars.io

### ISSUE THREAD

**Issue by systats** [EricSteinberger/PokerRL#12]
Hi Guys,

just wanna let you know that there is a Free Poker Bot Platform to test your agents in a more heterogenous environment. I think the current bots are already pretty competitive although it would be nice to compete against more ml experts. There are around 20-40 bots online almost 24/7.

Jump to [pokerwars leaderboard](https://www.pokerwars.io/stats) or check out several API languages on [pokerwars github](https://github.com/pokerwars)

Hope to see some of you there and exchange some insights.

Cheers,
Simon

**Comment by EricSteinberger** [comment]
Thanks Simon! Not planning on implementing this due to time constraints, but it's definitely cool.

Cheers,
Eric
