### ISSUE TITLE
Cannot use BR evaluation when game_cls == LimitHoldem

### ISSUE THREAD

**Issue by zj00377** [EricSteinberger/PokerRL#13]
Hi Eric, 

I have tried to use your paper experiment hyperparameter to train a model with game_cls = LImitHoldem. 

However, If I set the evaluation method is 'BR' (best response), then the program will abort in the staging of "Creating BR Mode Evaluator...", I wonder is there anything different between game_cls=  LImitHoldem and game_cls=StandardLeduc? If so, how could I modify the code accordingly in order to train the deepCFR model?

Thanks,
Joena

**Comment by EricSteinberger** [comment]
Yes, the code doesn't support BR for anything but Leduc. That's because that would take decades on a supercomputer to compute it against a deep learning algorithm :)
