### ISSUE TITLE
Could add simple example of "interactive_user_v_agent"?

### ISSUE THREAD

**Issue by shegood1985** [EricSteinberger/PokerRL#8]
Eric Steinberger,
Thank you for share such a greate framework of porker, Even I know little about machine learning, I still found much fun of this project. I am trying to make some fun of play poker with agent that use your algorithm, how can it works? Could you give a example about how to run with interactive_user_v_agent.py

**Comment by EricSteinberger** [comment]
This repo doesn't implement any algorithms aside tabular CFR variants. Check out https://github.com/EricSteinberger/Deep-CFR for Deep CFR and SD-CFR.
